name: duplicates

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup master repositories
      run: |
        sudo ./scripts/setup-master-gentoo.sh
    - name: Check for duplicates
      run: |
        ./scripts/check-duplicates.sh
